### PR TITLE
added a few appearances in the sed file that are unwanted

### PR DESCRIPTION
**Pull request by padeken**
Hi, I found a few things when using it with an old talk

### CODE REVIEW

**Comment by ast0815** [comment]
Doesn't the rule

```
#restore underscores
s|</*em>|_|g
```

remove all emphasises? Those are used in a later rule:

```
# Emphasis
s|<em>\(.*\)</em>|\\emph{\1}|g
```

I think there is a command line option for markdown2 that disables underscores as emphasis markers. You probably should recover the underscores there. Then asterisks can still be used for emphasis.

**Comment by padeken** [comment]
ok I will look into it

**Comment by padeken** [comment]
found the option this works better.

I now only have one problem where I have no solution:

\begin{align*}
formular
\end{align*}
is problematic but this is for an other day

**Comment by ast0815** [comment]
You could open an issue to keep track of the stuff that does not work as expected yet. ;)

**Pull request merged**
